version: '3.5'  

services: 
    frontend: 
      build: ./ml-kurkkumopo-frontend/
      image: frontendml
      ports: 
        - 3000:3000
    backend:
      build: ./ml-kurkkumopo-backend/
      image: backendml
      ports: 
        - 5000:5000
      volumes:
        - model:/src/model
    training:
      build: ./ml-kurkkumopo-training/
      image: training
      volumes:
        - model:/src/model
        - imgs:/src/imgs

volumes:
  model:
  imgs: