version: '3.5'  

services: 
    frontend: 
      image: frontend
      ports: 
        - 5000:5000
    backend:
      image: backend 
      environment:
        - REDIS=redis
        - DB_USERNAME=user
        - DB_PASSWORD=example
        - DB_HOST=db_backend
      ports: 
        - 8000:8000
      depends_on:
        - db
    redis:
      image: "redis:alpine"
    db:
      image: postgres
      restart: unless-stopped
      environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: example
      container_name: db_backend